// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Z-IqWR-wWciQUlHNz5u9atFuJOAG1iE',
    appId: '1:400626139894:web:25522f47d78566640d62d7',
    messagingSenderId: '400626139894',
    projectId: 'todo-app-7dcb4',
    authDomain: 'todo-app-7dcb4.firebaseapp.com',
    storageBucket: 'todo-app-7dcb4.appspot.com',
    measurementId: 'G-P2BNZW8YKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3K0jzDe0XxTRKE58AiaMHS9v4BWvQiNo',
    appId: '1:400626139894:android:c20469805db1cf8f0d62d7',
    messagingSenderId: '400626139894',
    projectId: 'todo-app-7dcb4',
    storageBucket: 'todo-app-7dcb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCLivHqi6ZNmRrANh2In2XJE0X38eDx7w',
    appId: '1:400626139894:ios:f64d388a11acf6070d62d7',
    messagingSenderId: '400626139894',
    projectId: 'todo-app-7dcb4',
    storageBucket: 'todo-app-7dcb4.appspot.com',
    iosClientId: '400626139894-b8cqvn6uh0t09mbsegb8e2168dc2d34v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCLivHqi6ZNmRrANh2In2XJE0X38eDx7w',
    appId: '1:400626139894:ios:f64d388a11acf6070d62d7',
    messagingSenderId: '400626139894',
    projectId: 'todo-app-7dcb4',
    storageBucket: 'todo-app-7dcb4.appspot.com',
    iosClientId: '400626139894-b8cqvn6uh0t09mbsegb8e2168dc2d34v.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );
}
